### ISSUE TITLE
[BUG] Import error parsing the package version

### ISSUE THREAD

**Issue by blmayer** [filipporomani/whatsapp#20]
I started getting this error after a while, maybe you updated the package in pypi:

```
[ERROR] ValueError: invalid literal for int() with base 10: '303post1'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/main.py", line 1, in <module>
    from config import client_whats, whatsapp_token, fb_verify_token, app_secret
  File "/config.py", line 15, in <module>
    client_whats = WhatsApp(whatsapp_token, whatsapp_number)
  File "/usr/local/lib/python3.11/site-packages/whatsapp/__init__.py", line 43, in __init__
    latest_int = int(latest.replace(".", ""))
```

I see this string `303post1` in your pyproject.toml file.

**Comment by filipporomani** [comment]
Sorry, I didn't explain well.

When you declare 
`client = WhatsApp(.....)` just use 
`client = WhatsApp(update_check=False)` instead

**Comment by blmayer** [comment]
Thanks for the patience, I'm not a good python programmer. And thanks again, it worked!

**Comment by filipporomani** [comment]
> Thanks for the patience, I'm not a good python programmer. And thanks again, it worked!

It's my fault, not yours @blmayer! Feel free to open an issue if you find any problem, I really appreciate that!
